/**
 * Livestream Flow Reference — auto-synced to #livestream-flow on startup.
 *
 * Each entry is an embed posted in order. On startup, the bot compares
 * existing embeds to this content and updates any that have changed.
 *
 * Updated 2026-05-03 to reflect the slash-command model.
 */

const messages = [
    // Message 1: Before Going Live
    {
        title: '📋 Stream Night Flow',
        description: [
            '**Before Going Live**',
            '```',
            'Queue is already open (opened by previous /offline)',
            'Pre-orders are coming in automatically via Stripe webhook',
            '/queue history                            → Check what\'s queued up tonight',
            '```',
            '',
            '**Pre-Stream Hype** (stream day, before going live)',
            '```',
            '/hype products:Product 1, Product 2      → Looks up products in Stripe',
            '                                            Shows preview with prices (detects sales)',
            '                                            Confirm with ✅ → posts to #announcements',
            '                                            Each product gets a Buy Now button',
            '```',
            '',
            '**Going Live**',
            '```',
            '/live                                    → Master switch ON',
            '                                            • Posts pre-order summary (queue stays OPEN)',
            '                                            • Starts livestream session',
            '                                            • Posts going-live in #announcements with shop link',
            '```',
        ].join('\n'),
        color: 0xceff00,
    },

    // Message 2: During Stream
    {
        title: '🔴 During Stream',
        description: [
            '```',
            'Work through the queue on stream         → Open each buyer\'s packs on camera',
            'Viewers buy from shop link                → Shipping handled at checkout',
            '',
            'CARD SALES:',
            '/sell args:@buyer "Card" 25.00           → Reserve for a viewer (30-min)',
            '/list open + /list add                    → Open a batch list',
            '/pull open args:"Pull Box" 3.00 50       → Open pull box (auto-closes when sold out)',
            '/pull close                               → Close pull box, show revenue',
            '',
            'COUPON / FLASH DEAL:',
            '/coupon create amount:1000               → $10 off coupon active at checkout',
            '/coupon off                               → Deactivate when window ends',
            '',
            'PACK BATTLE:',
            '/battle start product:"Name" max:12      → Start battle',
            '/battle close                             → Close entries, show roster',
            '  → Open ALL packs on stream, check tcgrepublic.com',
            '/battle winner user:@user                 → Declare winner, assign Aha role',
            '',
            'END OF STREAM (duck race):',
            '/duckrace show                            → Show duck race roster',
            '  → Run race at online-stopwatch.com/duck-race',
            '/duckrace winner user:@user               → Declare winner, close queue, open next',
            '',
            'GIVEAWAY (if active):',
            '/giveaway close                           → Close entries (if not auto-closed)',
            '/spin random                              → Animated spin',
            '',
            'AD-HOC (use /op for free-form args):',
            '/op shipping @user 10.00 [reason]        → Send a shipping checkout link',
            '/waive user:@user                         → Waive shipping',
            '/op refund @user [amount] [reason]       → Refund most recent purchase',
            '/sold args:<message_id>                   → Mark a card listing as sold',
            '```',
        ].join('\n'),
        color: 0xceff00,
    },

    // Message 3: End of Stream
    {
        title: '📴 End of Stream',
        description: [
            '```',
            '/offline                                 → Master switch OFF',
            '                                            • Ends livestream session',
            '                                            • Ensures a queue is open for pre-orders',
            '                                            • Posts stream-ended in #announcements',
            '                                            • Posts stream recap to #analytics',
            '```',
            '',
            '**Note:** Shipping is handled proactively at checkout — no post-stream DMs needed.',
            '',
            '**Audit log:** Every command you ran during the stream is in `#ops-log` with operator + timestamp + result. Useful for retrospectives or debugging.',
        ].join('\n'),
        color: 0xceff00,
    },

    // Message 4: Card Night Structure
    {
        title: '🃏 Card Night Structure',
        description: [
            'Single card-night stream. Mon, Tue, Wed at 8PM EST. All vibes-based — no hard clock.',
            '',
            '**Card Night (Pokemon + Anime)**',
            'Simulcast: TikTok + Instagram (iPad). Twitch + YouTube (OBS) return when the external camera is back.',
            '```',
            'Open           → Welcome, tonight\'s lineup, show products, hype chat',
            'Pokemon        → Pack openings, product showcase, pack battles',
            'Activity break → Duck race, wheel spin, giveaway draw, pack battle finals',
            'Anime          → Weiss Schwarz, anime product showcase, pack battles',
            'Activity break → Second duck race or flash deal announcement',
            'Wind down      → Recap best pulls, thank buyers, shout out Discord',
            'Close          → End the simulcast cleanly',
            '```',
            '',
            '**After Dark — Coming Soon**',
            'When this segment launches, it\'ll run after card nights on Twitch + Instagram only (end YouTube and TikTok simulcast first; enable Twitch mature tag). Mature product, same revenue activities. Plumbing built; ETA TBD.',
            '',
            '**Gaming — Informal**',
            'Not part of card nights anymore. We game most days; timing varies; drop into #looking-for-group for whatever\'s running. Separate setup (PC + OBS + TikTok Studio).',
        ].join('\n'),
        color: 0xceff00,
    },

    // Message 5: Shipping Reference & Quick Links
    {
        title: '📦 Shipping Reference',
        description: [
            '**Domestic (US): $10/week  •  International (CA+): $25/month** *(DM to ship early)*',
            '```',
            'Normal shop (email entered)    →  Bot checks coverage → $10/$25 or skip',
            'Normal shop (email skipped)    →  Both options at checkout, buyer picks',
            'Discord buttons (/list, /hype) →  Bot checks → $10/$25 or skip',
            'Pack battle buy-in             →  No shipping (winner pays after declaration)',
            'Ad-hoc (/op shipping @user N)  →  Any amount, DM with checkout link',
            '```',
            '',
            '*One payment covers all purchases for the period. Already paid = skipped.*',
            '*Orders auto-create in ShippingEasy. Tracking auto-imports when labels are purchased.*',
            '',
            '**Quick Links**',
            '```',
            'Duck race timer   → online-stopwatch.com/duck-race',
            'Card values       → tcgrepublic.com',
            'Shop              → itzenzo.tv',
            'Pricing formula   → cost × 1.45, round up',
            '```',
        ].join('\n'),
        color: 0xceff00,
    },

    // Message 6: Revenue Notes
    {
        title: '💰 Revenue Notes',
        description: [
            '```',
            'Pack battle math:',
            '  12 entries × full retail = 12 packs sold, winner gets all cards',
            '  The entertainment IS the value-add — no discounts',
            '',
            'Duck race cost:',
            '  1 free pack per race × 2 races per stream = ~$8-10/night',
            '  This is customer acquisition cost — worth it',
            '',
            'Activity breaks between segments:',
            '  1. Reward buyers publicly (encourages more purchases)',
            '  2. Create clip-worthy moments for TikTok/YouTube',
            '  3. Give you breathing room between selling segments',
            '',
            'Shipping model:',
            '  Email capture at checkout → bot checks coverage → skip if paid',
            '  One shop link for everyone — no special livestream URL needed',
            '  First purchase pays shipping, all subsequent skip for the period',
            '```',
        ].join('\n'),
        color: 0xceff00,
    },
];

export default messages;
